### ISSUE TITLE
Power Issues Megathread

### ISSUE THREAD

**Issue by SomeRandomOwl** [NovaSector/NovaSector#1678]
## Issue Summary

This is to report any power related issue related to ANY Nova specific item. If it isn't nova specific it may be best to report it upstream in their mega thread I expect a few to popup that weren't initially caught. Below is at least the first one i was informed of.

- [ ] Synth Posicom
- [x] Multi Cell Chargers
- [x] Cell Medigun
- [x] stirling generator
- [x] fontier lathe
- [x] Fontier coffee machine
- [x] wind turbine
- [x] ore thumper
- [x] Roundstart SMES on NOVA maps
- [x] synth charging
- [x] wall mounted multi cell charger

**Comment by TripleShades** [comment]
Pretty much everything from the flatpack system that generates power is barely pulling its own weight now. Dont know about flatpack machines that take power, but likely also those, as well as any cargo import that takes or gives power.

**Comment by OrbisAnima** [comment]
be aware, with the new system two regular cell chargers in an apc will drain it, even if the multi is fixed, the power draw of the change will make it unusable

**Comment by Thlumyn** [comment]
Round 10468; multi cell charges are recharging at an extremely low rate. Even a single cell charger (which do charge at a better rate) is enough to drain a room's APC.

**Comment by Zergspower** [comment]
Synth's cant charge : (

**Comment by Iajret** [comment]
> Pretty much everything from the flatpack system that generates power is barely pulling its own weight now. Dont know about flatpack machines that take power, but likely also those, as well as any cargo import that takes or gives power.

Could you elaborate on that, please? As far as i see, only stirlings seems to be making about half the power they show on display (had 8 installed with 38 KW each and getting only 160 total). Not even sure if that havent happened before this power rework thing.

**Comment by TripleShades** [comment]
> > Pretty much everything from the flatpack system that generates power is barely pulling its own weight now. Dont know about flatpack machines that take power, but likely also those, as well as any cargo import that takes or gives power.
> 
> Could you elaborate on that, please? As far as i see, only stirlings seems to be making about half the power they show on display (had 8 installed with 38 KW each and getting only 160 total). Not even sure if that havent happened before this power rework thing.

The flatpack RTGs and wind turbines are the ones I have experience with, and I realized that they're not an upstream thing, so it's likely affecting everything unique to Nova that you can order from cargo (where applicable), flatpacks included.
Three wind turbines used to be enough to power mining base, and now you need more like eight. A fully setup Interdyne with RTGs (five of them upgraded with bluespace) used to be plenty to do routine tasks in botany and chemistry easily, while now you will sometimes get brown-outs. It's a little scary, to be honest.

**Comment by Iajret** [comment]
Can't confirm RTG working any more different than they were before. It's all comes down to new power system being differently balanced. Flatpacked RTG still output intended 7.5 KW and colonial lathes consumes exactly the same amount of power it did before. But stirlings are for sure provide half as much power as they should
<details>

![image](https://github.com/NovaSector/NovaSector/assets/8430839/6d8fbab8-e5df-4217-bea6-cefc5abdc53a)

</details>

**Comment by SomeRandomOwl** [comment]
I will make a pr soon to address the rest of these

**Comment by YehnBeep** [comment]
![image](https://github.com/NovaSector/NovaSector/assets/86855173/5b2ca3cc-cfed-4994-ab03-68b65542c822)

This is after over an hour of charging.

**Comment by SomeRandomOwl** [comment]
> ![image](https://private-user-images.githubusercontent.com/86855173/318461365-5b2ca3cc-cfed-4994-ab03-68b65542c822.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5ODIyNjYsIm5iZiI6MTcxMTk4MTk2NiwicGF0aCI6Ii84Njg1NTE3My8zMTg0NjEzNjUtNWIyY2EzY2MtY2ZlZC00OTk0LWFiMDMtNjhiNjU1NDJjODIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDE0MzI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmNDgyZjBiOTE3MzllMGRkOTY5MjA2Yzc1NjBkYzAwMTA2Y2YwYWRkN2IwZDA1MDkyZGVhNTJkYzhkYTllMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8L0UlWfpUuTjRu4caGKTulJvjZCdKRFjRs0oc1qrM8w)
> 
> This is after over an hour of charging.

this will probally get fixed when the multi cell charger gets fixed, ill work on that later tonight

**Comment by YehnBeep** [comment]
Inducers also charge APCs too slow to be useful

**Comment by YehnBeep** [comment]
> It appears that Gas Turbines are outputting about half of what they're generating

Also noticed on DS2 that the gas turbine's output on the UI and what the SMES sees weren't matching up.

Related, I want to bring up a higher level 'design' issue. Since it doesn't really appear that the "charging a cell takes more power than over 600 average suburban homes" concept is going to change, and considering this strains even a full-sized station power grid -

Smaller grids (DS2, interdyne, other ghost roles) are really kind of suffering for cell charging. Even if their base power outputs were doubled, they wouldn't be able to run a single cell charger at full speed (or likely even at 25% speed).

So, these smaller grids could use a lot of help/buffing to deal with this change.

**Comment by SomeRandomOwl** [comment]
> It appears that Gas Turbines are outputting about half of what they're generating https://i.gyazo.com/cee7fb4552538e9d9109d4e79513f42c.png

I can probally check, but itd be a upstream pr

**Comment by TripleShades** [comment]
The MOD plasma flower core instantly drains of energy when used in a MODsuit.

**Comment by YehnBeep** [comment]
> So, these smaller grids could use a lot of help/buffing to deal with this change.

I want to follow up on this again, since now there's the 200KW reactor.

So, while the reactor is an improvement, it's still a looming issue. If the reactor had nothing to power but a charger, you're looking at 20% charge rate. But of course, since there's a mini station/ship to power, in practice it's more like 10%... maybe even 5% charge rate. Assuming only one thing is ever charging at a time, which extended charge times means it's more likely someone else might want to charge something too. Also assuming 1MW charge flow which is below some equipment's capacity, so then, in other cases you might be looking at only being able to charge at 2.5%~5% the max rate.

I really don't feel that non-glacial charging speeds should be something gated to the main station and everyone else just has to suffer.

I'm aware there are cheese strategies - build a charger on a shuttle/pod if you have one, or use botany to make unlimited bluespace cells and treat them as disposable batteries or eat a charging plant - but plenty of people don't seem to know about these, or lack the gameplay knowledge to implement them.

So, I think it would be beneficial if decent charging speeds were moved a bit closer to pre-rework accessibility. Even if this means making "self powered" chargers or something rather than amping up grids.

**Comment by Sadboysuss** [comment]
Shouldn't be a problem anymore, comment if there is still problems
