### ISSUE TITLE
sol police helmet uses exact same code as normal sec helmet, to a tee

### ISSUE THREAD

**Issue by ghost** [NovaSector/NovaSector#1720]
## Issue Summary
the sol police helmet uses all the same code the normal sec helmet has, pepperproof and visor flipping to boot.

## Reproduction: check SPH stats, pepperproof, press z inhand, flip it up making it an invisible helmet (that balds you)
![Screenshot_366](https://github.com/NovaSector/NovaSector/assets/64584757/9c340afd-4ada-4b88-ba75-659cf1363ffb)
![Screenshot_365](https://github.com/NovaSector/NovaSector/assets/64584757/4b9fa192-446a-4fe9-ae9d-abab8dc3371b)

**Comment by OrionTheFox** [comment]
"Using the exact same code" is fully intended; it's a subtype of the security helmet so that it has the same stats, functions, and we can also save time on the description because it's so generic. Extremely common, especially with clothing.

The only actual bug is that it's inheriting the toggleability (which is our own fault - TG sec helmets dont have visors, so it probably wasn't considered when subtyping off of it)
Easy 2 line fix, sol helmet item just needs these vars set.
```
action_types = null
can_toggle = false
```

**Comment by TheSS13Melon** [comment]
I remember when I initially added this item on SR that it didn't have this issue. I wonder if something changed since then. Wierd. I can probably fix this soon.

**Comment by Sadboysuss** [comment]
/tg/ sec helmets have visors now, shouldn't be an issue anymore
