### ISSUE TITLE
Leash is missing it's sprite

### ISSUE THREAD

**Issue by Aether217** [NovaSector/NovaSector#2364]
Reporting client version: 515.1623

The leash does not have the sprite when it's attached to someone

![image](https://github.com/NovaSector/NovaSector/assets/80391087/cf5180f3-f28a-4a61-8b4b-baaf0c5133a1)
(To protect the bottom's identity we have censored their face)

Screenshot from the PR for comparison
![image](https://github.com/NovaSector/NovaSector/assets/80391087/1e4e3eb8-7c54-4fea-ae90-f095b898e39c)

## Round ID:
[10775](https://scrubby.melonmesa.com/round/10775)

## Testmerges:
- [[MODULAR] Adds a dice roll emote](https://github.com/NovaSector/NovaSector/pull/1556)
- [[PORT] [SEMI-MODULAR] [JANK] Ports the lovely Character Directory which was ported from Coyote Bayou](https://github.com/NovaSector/NovaSector/pull/183)
- [Ooey Gooey Slimegirl Buffs Vol. 1](https://github.com/NovaSector/NovaSector/pull/1661)
- [Adds more spawn location to moldies](https://github.com/NovaSector/NovaSector/pull/2134)
- [Ouroboros rejigging](https://github.com/NovaSector/NovaSector/pull/2088)
- [[Semi-Modular] Ports over additional Crusher varients from monkestation](https://github.com/NovaSector/NovaSector/pull/2238)
- [Neuters synthetic electrical damage ](https://github.com/NovaSector/NovaSector/pull/2300)
- [[MIRROR] Turns mush cap into an extorgan](https://github.com/NovaSector/NovaSector/pull/491)

**Comment by unit0016** [comment]
**Not a bug**; the beam was removed prior to these even hitting Nova Sector (https://github.com/effigy-se/effigy-se/pull/814/commits/8ba567b11441bbaf7a6ba899f42c77db820716c0, https://github.com/effigy-se/effigy-se/pull/814/commits/79d88cdf1e838e93197b134b144b54d0773c4907) due to the sheer number of ways it clashed with other systems and I flagged repeatedly that it was not included and that that screenshot from when it *was* included was for demonstrative purposes.

- Multi-Z: the beam qdel'd itself every time z-level change occured. Remaking the beam only worked if you were going UP a z-level; for whatever reason?? Screamed of ghosts in the machine.

- Resting / Laying down: Needed to do even more jank math to update offsets for this; which would be a bitch when also taking into account:

- Sprite Scaling: needed to somehow check for someone's approximate size in *every* possible way that could be changed; not just via prefs.
